### ISSUE TITLE
v0.10.10 release checklist

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1034]
See full [release checklist](https://github.com/sile-typesetter/sile/wiki/Release-Checklist) for howto, this is just a checklist version:

- [x] Pass all tests
- [x] Spring clean
- [x] Re-fetch tooling
- [x] Configure
- [x] Cut release
- [x] Push tag to master
- Update website
    - [x] Copy changelog and prefix with a summary as a blog post
    - [x] Copy and post manual, update 'latest' symlink and menu links
    - [x] Tweak summary and edit into Github release notes
- Update distro packages
    - [x] Arch Linux
    - [ ] Void Linux: [Pull Request](https://github.com/void-linux/void-packages/pull/18306)
    - [x] NixOS: [Pull Request](https://github.com/NixOS/nixpkgs/pull/95445)
    - [x] Homebrew: [Pull Request](https://github.com/Homebrew/homebrew-core/pull/59657)
    - [ ] BSD Ports: [mailing list thread](https://marc.info/?t=157907840200001)
    - [x] Ubuntu: [ppa](https://launchpad.net/~sile-typesetter/+archive/ubuntu/sile)
    - [x] Docker
- [x] Shuffle milestones
- [ ] Eat cake
