### ISSUE TITLE
v0.10.12 release checklist

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1083]
See full [release checklist](https://github.com/sile-typesetter/sile/wiki/Release-Checklist) for howto, this is just a checklist version:

- [x] Pass all tests
- [x] Spring clean
- [x] Re-fetch tooling
- [x] Configure
- [x] Cut release
- [x] Push tag to master
- Update website
    - [x] Copy changelog and prefix with a summary as a blog post
    - [x] Copy and post manual, update 'latest' symlink and menu links
    - [x] Tweak summary and edit into GitHub release notes
- Update distro packages
    - [x] Arch Linux: [aur](https://aur.archlinux.org/packages/sile)
    - [x] Homebrew: [pull request](https://github.com/Homebrew/homebrew-core/pull/62631)
    - [x] NixOS: [pull request](https://github.com/NixOS/nixpkgs/pull/100172)
    - [x] Ubuntu: [ppa](https://launchpad.net/~sile-typesetter/+archive/ubuntu/sile)
    - [x] Docker: [tags](https://hub.docker.com/repository/docker/siletypesetter/sile/tags)
    - [ ] NetBSD: pinging @jsonn re [pkgsrc](https://pkgsrc.se/print/sile)
    - [ ] Void Linux: [pull request](https://github.com/void-linux/void-packages/pull/18306)
    - [ ] OpenBSD: [mailing list thread](https://marc.info/?t=157907840200001)
- [x] Shuffle milestones
- [x] Eat cake
