### ISSUE TITLE
v0.10.14 release checklist

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1130]
Just like development cycles can be driven by different factors (conferences, tests, hypothesis, behavior, design, hype), releases can have different motivating factors. This release cycle brought to you by :cake: cake. My birthday was yesterday and between COVID-19 precautions and [city-wide flooding](https://twitter.com/DuvarEnglish/status/1356575608000679938), pretty much the only party attendee was the cake bearer, so I have a large surplus of chocolate cake.

That and I need the UTF-8 fixes in a stable release sooner rather than later so CaSILE in CI runners doesn't hang.

----

See full [release checklist](https://github.com/sile-typesetter/sile/wiki/Release-Checklist) for howto, this is just a checklist version:

- [x] Pass all tests
- [x] Spring clean
- [x] Re-fetch tooling
- [x] Configure
- [x] Cut release
- [x] Push tag to master
- Update website
    - [x] Copy changelog and prefix with a summary as a blog post
    - [x] Copy and post manual, update 'latest' symlink and menu links
    - [x] Tweak summary and edit into GitHub release notes
- Update distro packages
    - [x] Arch Linux: [aur](https://aur.archlinux.org/packages/sile)
    - [x] Homebrew: [pull request](https://github.com/Homebrew/homebrew-core/pull/70325)
    - [ ] NixOS: 
    - [ ] Ubuntu: [ppa](https://launchpad.net/~sile-typesetter/+archive/ubuntu/sile)
    - [x] Docker: [tags](https://hub.docker.com/repository/docker/siletypesetter/sile/tags)
    - [ ] NetBSD: 
    - [ ] Void Linux: [pull request](https://github.com/void-linux/void-packages/pull/18306)
    - [ ] OpenBSD: [mailing list thread](https://marc.info/?t=157907840200001)
- Bump downstream projects
    - [ ] [FontProof](https://github.com/sile-typesetter/fontproof) (Docker image base plus CI matrix)
- [x] Shuffle milestones
- [x] Eat cake

**Comment by alerque** [comment]
Closing because a new release is about to be cut. Platforms that didn't get updated will just skip to the next release.
