### ISSUE TITLE
v0.10.15 release checklist

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1158]
See full [release checklist](https://github.com/sile-typesetter/sile/wiki/Release-Checklist) for howto, this is just a checklist version:

- [x] Pass all tests
- [x] Spring clean
- [x] Re-fetch tooling
- [x] Configure
- [x] Cut release
- [x] Push tag to master
- Update website
    - [x] Copy changelog and prefix with a summary as [a blog post](https://sile-typesetter.org/2021/03/sile-0-10-15-is-released)
    - [x] Copy and post manual, update 'latest' symlink and menu links
    - [x] Tweak summary and edit into [GitHub release notes](https://github.com/sile-typesetter/sile/releases/tag/v0.10.15)
- Update distro packages
    - [x] Arch Linux: [aur](https://aur.archlinux.org/packages/sile)
    - [x] Homebrew: [pull request](https://github.com/Homebrew/homebrew-core/pull/72315)
    - [x] NixOS: [pull request](https://github.com/NixOS/nixpkgs/pull/114858)
    - [x] Ubuntu: [ppa](https://launchpad.net/~sile-typesetter/+archive/ubuntu/sile)
    - [x] Docker: [tags](https://hub.docker.com/repository/docker/siletypesetter/sile/tags)
    - [x] NetBSD: pinging @jsonn re [pkgsrc](https://pkgsrc.se/print/sile)
    - [ ] Void Linux: [pull request](https://github.com/void-linux/void-packages/pull/18306)
    - [ ] OpenBSD: [mailing list thread](https://marc.info/?t=157907840200001)
- Bump downstream projects
    - [ ] [FontProof](https://github.com/sile-typesetter/fontproof) (Docker image base plus CI matrix)
- [x] Shuffle milestones
- [ ] Eat cake

Note some items in #1130 from v0.10.14 release were not finished.

**Comment by alerque** [comment]
@jsonn or anybody else seeing this in relation to NetBSD: Since the port for this hasn't been bumped since v0.10.12 I'll just note here the most important change: v0.10.14 added a dependency on the Lua Rock `luautf8`. Also this release should *not* need `bash` as a build dependency. Otherwise packaging should be just a matter of bumping...

**Comment by jsonn** [comment]
Thanks, looks good. I'll commit tomorrow or so.

**Comment by alerque** [comment]
New as of this release for the Ubuntu world (not universe), [our PPA now covers Groovy and Hirsute](https://sile-typesetter.org/2021/03/ubuntu-ppa-now-covers-groovy-and-hirsute).

I've been pretty sick and avoiding sugar during recovery, hence no cake for me this release cycle but I think we can call this one done.
