### ISSUE TITLE
v0.11.0 release checklist

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1199]
See full [release checklist](https://github.com/sile-typesetter/sile/wiki/Release-Checklist) for howto, this is just a checklist version:

- [x] Pass all tests
- [x] Spring clean
- [x] Re-fetch tooling
- [x] Configure
- [x] Cut release
- [x] Push tag to master
- Update website
    - [x] Copy changelog and prefix with a summary as a blog post
    - [x] Copy and post manual, update 'latest' symlink and menu links
    - [x] Tweak summary and edit into GitHub release notes
- Update distro packages
    - [x] Arch Linux: [aur](https://aur.archlinux.org/packages/sile)
	- [ ] Homebrew: [pull request](https://github.com/Homebrew/homebrew-core/pull/84477)
	- [ ] NixOS: [pull request](https://github.com/NixOS/nixpkgs/pull/136431), [related pull request](https://github.com/NixOS/nixpkgs/pull/136453)
    - [ ] Ubuntu: [ppa](https://launchpad.net/~sile-typesetter/+archive/ubuntu/sile)
    - [x] Docker: [tags](https://hub.docker.com/repository/docker/siletypesetter/sile/tags)
	- [x] GHCR: [versions](https://github.com/orgs/sile-typesetter/packages/container/sile/versions)
	- [ ] NetBSD: pinging @jsonn re [pkgsrc](https://pkgsrc.se/print/sile)
    - [ ] Void Linux: [pull request](https://github.com/void-linux/void-packages/pull/18306)
    - [ ] OpenBSD: [mailing list thread](https://marc.info/?t=157907840200001)
- Bump downstream projects
    - [ ] [FontProof](https://github.com/sile-typesetter/fontproof) (Docker image base plus CI matrix)
- [x] Shuffle milestones
- [ ] Eat cake

**Comment by alerque** [comment]
And ... it seems with this release Docker Hub has gone the way of Travis CI and left open source in the lurch. Automated builds now require a subscription.

We already build Docker images that end up in GitHub [Package Repository](https://github.com/orgs/sile-typesetter/packages/container/package/sile) anyway for use in running GitHub actions. We can also build them using Cirrus. I'll look into how to just push prebuilt images from elsewhere to Docker Hub for the convenience of anybody downloading it from there.

**Comment by ctrlcctrlv** [comment]
@alerque Can you apply the patch in #1197? (That is, update NanoSVG dependency?)

**Comment by alerque** [comment]
Closing in favor of #1204. Downstream packaging turned up a couple issues that we can fix easier with a patch release than make distro packagers work around downstream.
