### ISSUE TITLE
v0.12.0 release checklist

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1247]
See also [website tracking issue](https://github.com/sile-typesetter/sile-typesetter.github.io/issues/19) for announcing math.

- [x] Pass all tests
- [x] Spring clean
- [x] Re-fetch tooling
- [x] Configure
- [x] Cut release
- [x] Push tag to master
- Update website
    - [x] Copy changelog and prefix with a summary as a blog post
    - [x] Copy and post manual, update 'latest' symlink and menu links
    - [x] Tweak summary and edit into GitHub release notes
- Update downstream distro packages
	- [x] Arch Linux official: [community/sile](https://archlinux.org/packages/community/x86_64/sile/)
	- [x] Arch Linux AUR: [AUR/sile-luajit](https://aur.archlinux.org/packages/sile-luajit) 
	- [x] Homebrew: [Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/sile.rb) — [pull request](https://github.com/Homebrew/homebrew-core/pull/85727)
	- [x] NixOS: [nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/sile/default.nix) — [pull request](https://github.com/NixOS/nixpkgs/pull/138957)
	- [x] Ubuntu: [ppa](https://launchpad.net/~sile-typesetter/+archive/ubuntu/sile)
	- [x] Docker Hub: [tags](https://hub.docker.com/repository/docker/siletypesetter/sile/tags)
	- [x] GHCR: [versions](https://github.com/orgs/sile-typesetter/packages/container/sile/versions)
	- [ ] NetBSD: pinging @jsonn re [pkgsrc](https://pkgsrc.se/print/sile)
    - [ ] Void Linux: 
    - [ ] OpenBSD: 
- Bump downstream projects
    - [ ] [FontProof](https://github.com/sile-typesetter/fontproof) (Docker image base plus CI matrix)
- [x] Shuffle milestones
- [ ] Eat cake

**Comment by simoncozens** [comment]
This one's worth sleeping on.

**Comment by alerque** [comment]
@jsonn There shouldn't be any significant changes required for packaging this release (or any in the v0.11.x series NetBSD skipped), but if you have any issues please don't hesitate to get in touch. There have been some bumps to Lua dependencies, but none of them are required.
