### ISSUE TITLE
Clarifying weird units, please...

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1267]
(a) In the "image" package documentation:
> If the size parameters are not given, then the image will be output at its ‘natural’ pixel size.

And the examples go on with several widths in **px** (pixels?)

But what does it mean? If I give a width of 50px, it doesn't seem much different than 50pt apparently. So I am lost here, what is this "px" unit on the images, exactly?

(b) In the "svg" package documentation:
> Optional width or height options will scale the SVG canvas to the given size calculated at a given density option (which defaults to 72 ppi).

So now we have a new **ppi** (points per inch, I assume), and I am lost again. Changing the density from 1 to 600 didn't seem to affect the output in my raw test. Huh. 72ppi (the so-said default) looks like a screen resolution of some sort, but why? All I want is to ensure that in print, I'd have at least, say, 300 **dpi** (yeah, let me introduce another unit...) if things have to be rasterized at some point. Do they, for SVG? What I am supposed to understand and do?

(c) _Where it goes even weirder_

So we have "SILE.**length**(...)" in several places (sometimes behind a `SU.cast(..)` - which I realize I have abused in my own use of it - a length can have a plus or minus (shrink/stretch).

But we also have SILE.**measurement**` in other commands. And the SILE manual doesn't describe it, but the behavior is different. Wow... Sounds messy, when these concepts aren't introduced properly...

But besides a documentation issue (and a consistency issue between packages?), it goes even further... Some length/measurement values are actually passed via yet another mean: `SILE.parseComplexFrameDimension` - The "raiselower" and "image" package do this.... Huh? Wait, this method understands **frame-related specifications**, and I am sort of amazed, but it actually works:

```
\img[src=documentation/gutenberg.png, width=width(content)]
```
Wow... real weird.... Was this intended? But if so, it fails on the  "svg" package, which will not accept such a width specification. Doh.

_Let's recap_ : length vs. measurement, pt vs. px or  ppi, ordinary units vs. frame-style width. ~~Isn't there some inconsistency to fix? Maybe not: Frankly, I got lost.~~ Update: 

- [x] Length vs. measurement = documentation issue --> See #1768
- [x] SVG ppi = likely hides a bug #1449 - marked as done here since it now has its own bug issue
- [x] Image size = documentation issue, fixed in #1277 
- [x] Use of frame dimensions in some unrelated commands = likely a bug. Notably to consider/investigate
  - [x] imagedata in dockbook class --> Tracked as #1767 so marked as done here since it now has its own bug issue
  - [x] img (image package) --> fixed in #1500 (third point)
  - [x] raise/lower (raiselower package) --> fixed in #1506
  - [x] grid (grid package) --> fixed (changed to a measurement in f2924fc8c4ac7aa0c51c7b073b6ff943320eb212)

**Comment by ctrlcctrlv** [comment]
I've had many of your same problems and these are the answers, whether or not they make sense is a matter of opinion:

(a) SILE has no `px` unit. All bare numbers, as in `packages/image`, therefore default to `pt`: https://github.com/sile-typesetter/sile/blob/master/core/measurement.lua#L45-L48

(b) SVG package does no rasterization at all. So it doesn't matter what ppi you say, you'll always get high quality vectors in your PDF. If you give a `density` > 72, then it will scale the width/height box it outputs your SVG into. https://github.com/sile-typesetter/sile/blob/985b9c3188ef9ee55046215aa2a94cf4f96d35f7/packages/svg.lua#L18

(c) `SILE.length` is backed by `SILE.measurement`, which is a class representing any possible SILE measurement. `SILE.length` provides convenience functions for creating `SILE.measurement`'s (in my understanding, feel free to expand on this basic description if you are more knowledgeable.) See `core/length.lua` and `core/measurement.lua`.

**Comment by ctrlcctrlv** [comment]
Also, yes, it's absolutely intended for you to be able to say things like `width(content)`, these are very useful ways of creating measurements. You can also say `50%fh` (50% of the height of the frame I'm writing into), `50%fw`, and further `50%pw` (50% of the width of the page I'm writing into), etc.

**Comment by Omikhleia** [comment]
> Also, yes, it's absolutely intended for you to be able to say things like `width(content)`, these are very useful ways of creating measurement

Only on the few commands that use `parseComplexFrameDimension` (e.g. image and raise/lower). This seems to be a discrepancy with the other units.

**Comment by Omikhleia** [comment]
To clarify, my suggestion would be
- to kill the reference to px in "image"
- to deprecate the ppi stuff in "svg"
- to check why some commands use frame dimensions instead of length/measurement units
- to document measurements in the manual

**Comment by Omikhleia** [comment]
>   to kill the reference to px in "image" (EDIT and/or say an image pixel is rendered as a point (pt) by default), and use pt in the examples afterwards.)

And after more testing, the above is slightly untrue. The image resolution (as encoded, e.g. in a PNG etc.) is honored if the width/height are not set. Which is what the "natural size" in the documentation probably meant - but the "Here is a 200x243 pixel image output" is then still misleading.

The original image is 200x243 pixels but with a resolution at approx. 95.987 pixels/in - ending up to a "natural size" of approx. 2.094 x 2.532 in on the printed page.

The very same image, still 200x243 pixels, could be saved with a claimed resolution at 150 pixels/in - ending up to a "natural size" of approx 1.333 x 1.620 in. And indeed:

![image](https://user-images.githubusercontent.com/18075640/140915422-b0a44b8e-7f2b-4446-988f-fad4332cb0fd.png)

**Comment by ctrlcctrlv** [comment]
Interesting, and definitely worth a documentation patch…

**Comment by Omikhleia** [comment]
And thus the ppi density stuff in svg could make some sense too - it would assume a "natural size" for the canvas units. I couldn't making it work though (I don't observe any difference with a random SVG for which I do not provide no width/height but only a density - so there might be an actual bug here).

**Comment by ctrlcctrlv** [comment]
@Omikhleia What about the `viewBox`? An SVG does not always need to include a width/height.

**Comment by Omikhleia** [comment]
My random SVG has both visibly:
```
<svg
   version="1.1"
   id="Layer_1"
   x="0px"
   y="0px"
   viewBox="0 0 1599.9996 1599.9988"
   enable-background="new 0 0 1625.869 1625.869"
   xml:space="preserve"
   sodipodi:docname="15916331801591631879159163111615916269721545769933.svg"
   width="1599.9996"
   height="1599.9988"
   inkscape:version="1.1 (ce6663b3b7, 2021-05-25)"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg"><defs
   id="defs231" /><sodipodi:namedview
   id="namedview229"
   pagecolor="#ffffff"
   bordercolor="#666666"
   borderopacity="1.0"
   inkscape:pageshadow="2"
   inkscape:pageopacity="0.0"
   inkscape:pagecheckerboard="0"
   showgrid="false"
   fit-margin-top="0"
   fit-margin-left="0"
   fit-margin-right="0"
   fit-margin-bottom="0"
   inkscape:zoom="0.51910701"
   inkscape:cx="798.48662"
   inkscape:cy="952.59743"
   inkscape:window-width="1848"
   inkscape:window-height="1016"
   inkscape:window-x="72"
   inkscape:window-y="27"
   inkscape:window-maximized="1"
   inkscape:current-layer="Layer_1" />
```

**Comment by ctrlcctrlv** [comment]
Yes, but `viewBox` is also not required; you can have either width/height+viewBox, or just width/height, or just viewBox, or I think none?

**Comment by alerque** [comment]
There is definitely some documentation that needs clarifying here, but let me just step in with the low hanging fruit:

* `SILE.measurement` is a basic construct with an amount and a unit.
* `SILE.length` is a more advanced construct composed of *3 measurements*: a base measurement, a stretch measurement, and a shrink measurement.

Both of these are used for various purposes, and in some cases they are nearly interchangeable. Casting from one to the other is easy is most cases: casting a length to a measurement returns just the base measurement and discards the stretch and shrink properties, the other way adds zero value measurements for the additional properties.

Using `SILE.measurement` is faster (1/3 the math) whenever flexibility is not in question, but `SILE.length` should be used anywhere those values *could* be non-zero.

**Comment by Omikhleia** [comment]
As of now, the checkboxes from the original issue are all addressed, or tracked separately, except "Length vs. measurement = documentation issue" --> Self-assigning.

**Comment by Omikhleia** [comment]
Ticking the last checkox with #1758. Pfew, took me 1+ year to sort this out :)
