### ISSUE TITLE
v0.12.1 release checklist

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1305]
See full [release checklist](https://github.com/sile-typesetter/sile/wiki/Release-Checklist) for howto, this is just a checklist version:

- [x] Spring clean
- [x] Re-fetch tooling
- [x] Configure and build
- [x] Pass all tests
- [x] Cut release
- [x] Push tag to master
- Update website
    - [x] Copy changelog and prefix with a summary as a blog post
    - [x] Copy and post manual, update 'latest' symlink and menu links
    - [x] Tweak summary and edit into GitHub release notes
    - [x] Drop devel flag from any examples that were using it
- Update downstream distro packages
	- [x] Arch Linux official: [community/sile](https://archlinux.org/packages/community/x86_64/sile/)
	- [x] Arch Linux AUR: [AUR/sile-luajit](https://aur.archlinux.org/packages/sile-luajit) 
	- [x] Homebrew: [Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/sile.rb) [pull request](https://github.com/Homebrew/homebrew-core/pull/92999)
	- [x] NixOS: [nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/sile/default.nix) [pull request](https://github.com/NixOS/nixpkgs/pull/154806)
	- [x] Ubuntu: [ppa](https://launchpad.net/~sile-typesetter/+archive/ubuntu/sile)
	- [x] Docker Hub: [tags](https://hub.docker.com/repository/docker/siletypesetter/sile/tags)
	- [x] GHCR: [versions](https://github.com/orgs/sile-typesetter/packages/container/sile/versions)
	- [ ] NetBSD: pinging @jsonn re [pkgsrc](https://pkgsrc.se/print/sile)
    - [ ] Void Linux: 
	- [ ] OpenBSD: [mailing list thread](https://marc.info/?t=157907840200001)
- Bump downstream projects
    - [x] [FontProof](https://github.com/sile-typesetter/fontproof) (Docker image base plus CI matrix)
- [x] Shuffle milestones
- [ ] Eat cake

**Comment by alerque** [comment]
All the remaining distro bumps are ones that are out of our purview. I'm going to find cake, I think there might be some leftover brownies is the fridge.
