### ISSUE TITLE
v0.12.2 release checklist

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1310]
See full [release checklist](https://github.com/sile-typesetter/sile/wiki/Release-Checklist) for howto, this is just a checklist version:

- [x] Spring clean
- [x] Re-fetch tooling
- [x] Configure and build
- [x] Pass all tests
- [x] Cut release
- [x] Push tag to master
- Update website
    - [x] Copy changelog and prefix with a summary as a blog post
    - [x] Copy and post manual, update 'latest' symlink and menu links
    - [x] Tweak summary and edit into GitHub release notes
    - [x] Drop devel flag from any examples that were using it
- Update downstream distro packages
	- [x] Arch Linux official: [community/sile](https://archlinux.org/packages/community/x86_64/sile/)
	- [x] Arch Linux AUR: [AUR/sile-luajit](https://aur.archlinux.org/packages/sile-luajit) 
	- [x] Homebrew: [Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/sile.rb) [pull request](https://github.com/Homebrew/homebrew-core/pull/93998)
	- [x] NixOS: [nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/sile/default.nix) [pull request](https://github.com/NixOS/nixpkgs/pull/157145)
	- [x] Ubuntu: [ppa](https://launchpad.net/~sile-typesetter/+archive/ubuntu/sile)
	- [x] Docker Hub: [tags](https://hub.docker.com/repository/docker/siletypesetter/sile/tags)
	- [x] GHCR: [versions](https://github.com/orgs/sile-typesetter/packages/container/sile/versions)
    - [ ] NetBSD: 
    - [ ] Void Linux: 
    - [ ] OpenBSD: 
- Bump downstream projects
    - [ ] [FontProof](https://github.com/sile-typesetter/fontproof) (Docker image base plus CI matrix)
- [ ] Shuffle milestones
- [ ] Eat cake

**Comment by alerque** [comment]
**PPA Change Alert**

With this release, I've automated more of the PPA release cycle for Ubuntu. This brings a few changes to the build matrix:

* Dropped support for discontinued releases (Groovy, Hirsute)
* Added support for more current releases (Impish, Jammy)
* Dropped i386 builds
* Added armv7 and armv8 builds

c.f. #1312
