### ISSUE TITLE
v0.13.0 release checklist

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1418]
See full [release checklist](https://github.com/sile-typesetter/sile/wiki/Release-Checklist) for howto, this is just a checklist version:

- [x] Spring clean
- [x] Re-fetch tooling
- [x] Configure and build
- [x] Pass all tests
- [x] Cut release
- [x] Push tag to master
- Update website
    - [x] Copy changelog and prefix with a summary as a blog post
    - [x] Copy and post manual, update 'latest' symlink and menu links
    - [x] Tweak summary and edit into GitHub release notes
    - [x] Drop devel flag from any examples that were using it
- Update downstream distro packages
	- [x] Arch Linux official: [community/sile](https://archlinux.org/packages/community/x86_64/sile/)
	- [x] Arch Linux AUR: [AUR/sile-luajit](https://aur.archlinux.org/packages/sile-luajit) 
	- [x] Homebrew: [Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/sile.rb) – [pull request](https://github.com/Homebrew/homebrew-core/pull/103334)
	- [x] NixOS: [nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/sile/default.nix) – [pull request](https://github.com/NixOS/nixpkgs/pull/177079) – [tracker](https://nixpk.gs/pr-tracker.html?pr=177079)
	- [x] Ubuntu: [ppa](https://launchpad.net/~sile-typesetter/+archive/ubuntu/sile)
	- [x] Docker Hub: [tags](https://hub.docker.com/repository/docker/siletypesetter/sile/tags)
	- [x] GHCR: [versions](https://github.com/orgs/sile-typesetter/packages/container/sile/versions)
    - [ ] NetBSD: 
    - [ ] Void Linux: 
    - [ ] OpenBSD: 
- Bump downstream projects
    - [ ] [FontProof](https://github.com/sile-typesetter/fontproof) (Docker image base plus CI matrix)
- [x] Shuffle milestones
- [ ] Eat cake

**Comment by alerque** [comment]
After 992 Gigs (Yes a terrabyte) of builds spread across 33 LXC containers and hundreds of builds while generally bashing my head against Launchpad, Ubuntu builds just landed. Such a fiasco. I hope somebody out there is actually using SILE on Ubuntu...

FontProof might need some work, but we can track that in the [relevant PR over there](https://github.com/sile-typesetter/fontproof/pull/36).

**Comment by Omikhleia** [comment]
> I hope somebody out there is actually using SILE on Ubuntu...

I do, at this date. (The future is always uncertain. One can never know... After all, I began years ago on a Slackware :rofl: 

I have no idea how it is in other countries, but I attended a few events here in France where there are Linux install parties proposed to non tech-savvy people, and if they have no idea what they actually want, they usually get Ubuntu. (Aside story: when my wife could not update her old laptop from Win7 to Win10, she asked about switching to Linux. I didn't want to do it --for reasons-- so she went to such an install party and she came back with an Ubuntu.)

Anyway, kudos for the effort :rocket:
