### ISSUE TITLE
v0.14.3 release checklist

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1551]
- [x] Shuffle any issues being put off to future milestones
- [x] Close all issues in current milestone (except this one)
- [x] Spring clean
- [x] Re-fetch tooling
- [x] Configure and build
- [x] Pass all tests
    - [x] Remote CI
    - [x] Local
- [x] Cut release
- [x] Push release commit & tag to master
- Update website
    - [x] Copy and post manual, update 'latest' symlink and menu links
    - [x] Copy changelog and prefix with a summary as a blog post
    - [x] Tweak summary for gfm and edit into GitHub release notes
- Update downstream distro packages
	- [x] Arch Linux official: [community/sile](https://archlinux.org/packages/community/x86_64/sile/)
	- [x] Arch Linux AUR: [AUR/sile-luajit](https://aur.archlinux.org/packages/sile-luajit) 
	- [x] Homebrew: [Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/sile.rb) – [pull request](https://github.com/Homebrew/homebrew-core/pull/109429)
	- [x] NixOS: [nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/sile/default.nix) – [pull request](https://github.com/NixOS/nixpkgs/pull/189352) – [tracker](https://nixpk.gs/pr-tracker.html?pr=189352)
		- [x] Drop devel flag from any website examples that were using it
	- [x] Ubuntu: [ppa](https://launchpad.net/~sile-typesetter/+archive/ubuntu/sile)
	- [x] Docker Hub: [tags](https://hub.docker.com/repository/docker/siletypesetter/sile/tags)
	- [x] GHCR: [versions](https://github.com/orgs/sile-typesetter/packages/container/sile/versions)
	- [x] openSUSE: pinging @Pi-Cla re [specfile](https://build.opensuse.org/package/show/home:Pi-Cla/sile)
	- [ ] NetBSD: pinging @jsonn re [pkgsrc](https://pkgsrc.se/print/sile)
    - [ ] Void Linux: 
    - [ ] OpenBSD: 
- Bump downstream projects
    - [ ] [FontProof](https://github.com/sile-typesetter/fontproof) (Docker image base plus CI matrix)
    - [x] [CaSILE](https://github.com/sile-typesetter/casile) (check, consider patch release)
- [ ] Eat cake

[![Packaging status](https://repology.org/badge/vertical-allrepos/sile.svg)](https://repology.org/project/sile/versions)

**Comment by alerque** [comment]
@Pi-Cla That's great. Be sure and ping me when the Lua deps land and your package gets upstreamed. I'll drop a quick blog post or mention in in the next release notes.

**Comment by jameschensmith** [comment]
@alerque, is there a reason SILE is marked as broken in the Nix package for the Darwin platform ([view here](https://github.com/NixOS/nixpkgs/blob/89d52414c6bc07f1aecd5ae5651febb7aa1238bb/pkgs/tools/typesetting/sile/default.nix#L109))? It looks like this was [marked broken ~3 months ago](https://github.com/NixOS/nixpkgs/commit/cd3c25616d603598d32430e30ae676f93959f6bd) when SILE was v0.12.5.

**Comment by alerque** [comment]
@jameschensmith Not to my knowledge. I didn't understand why it was marked that way to begin with nor why it still is. If there is something we can fix on our end I'd be happy to. I think it might have had to do with a Lua dependency that didn't build but if so don't recollect which one.

**Comment by alerque** [comment]
@jameschensmith I opened https://github.com/NixOS/nixpkgs/pull/189582 to try to identify if there is actually a problem and if so what the root cause is. If you happen to be able to actually test drive it on Darwin that would probably help.
