### ISSUE TITLE
v0.14.6 release checklist

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1653]
- [x] Shuffle any issues being put off to future milestones
- [x] Close all issues in current milestone (except this one)
- [x] Spring clean
    - [x] Re-fetch tooling
- [x] Configure and build
- [x] Pass all tests
    - [x] Remote CI
    - [x] Local
- [x] Cut release
- [x] Push release commit & tag to master
- Update website
    - [x] Copy and post manual, update 'latest' symlink and menu links
    - [x] Copy changelog and prefix with a summary as a blog post
    - [x] Tweak summary for gfm and edit into GitHub release notes
- Update downstream distro packages
	- [x] Arch Linux official: [community/sile](https://archlinux.org/packages/community/x86_64/sile/)
	- [x] Arch Linux AUR: [AUR/sile-luajit](https://aur.archlinux.org/packages/sile-luajit) 
    - [ ] Homebrew: [Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/sile.rb) – [pull request](https://github.com/Homebrew/homebrew-core/pull/118254)
    - [ ] NixOS: [nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/sile/default.nix) – [pull request](https://github.com/NixOS/nixpkgs/pull/206284) – [tracker](https://nixpk.gs/pr-tracker.html?pr=206284)
        - [ ] Drop devel flag from any website examples that were using it
    - [x] Ubuntu: [ppa](https://launchpad.net/~sile-typesetter/+archive/ubuntu/sile)
    - [x] Docker Hub: [tags](https://hub.docker.com/repository/docker/siletypesetter/sile/tags)
    - [x] GHCR: [versions](https://github.com/orgs/sile-typesetter/packages/container/sile/versions)
    - [x] openSUSE: pinging @Pi-Cla re [specfile](https://build.opensuse.org/package/show/openSUSE%3AFactory/sile)
    - [ ] Fedora: pinging @hegjon re [copr](https://copr.fedorainfracloud.org/coprs/jonny/SILE/)
    - [ ] NetBSD: pinging @jsonn re [pkgsrc](https://pkgsrc.se/print/sile)
    - [ ] Void Linux: [pull request](https://github.com/void-linux/void-packages/pull/18306)
    - [ ] OpenBSD: [mailing list thread](https://marc.info/?t=157907840200001)
- Bump downstream projects
    - [ ] [FontProof](https://github.com/sile-typesetter/fontproof) (Docker image base plus CI matrix)
    - [ ] [CaSILE](https://github.com/sile-typesetter/casile) (check, consider patch release)
- [ ] Eat cake

[![Packaging status](https://repology.org/badge/vertical-allrepos/sile.svg)](https://repology.org/project/sile/versions)

**Comment by Pi-Cla** [comment]
I have been updating openSUSE's package in the background, and here is the latest SR! https://build.opensuse.org/request/show/1043025 (once it is accepted it will go into the next daily release of openSUSE Tumbleweed)

**Comment by uncomfyhalomacro** [comment]
@Pi-Cla oh thanks for packaging sile. i have forgotten.

**Comment by hegjon** [comment]
Building for Fedora Linux on COPR now https://copr.fedorainfracloud.org/coprs/jonny/SILE/build/5147404/

**Comment by alerque** [comment]
@hegjon It looks like the COPR build got hung up finding Genitum Plus:

```
checking whether font family Gentium Plus is available... configure: error: in `/builddir/build/BUILD/sile-0.14.6':
configure: error: font family Gentium Plus not found
```

I bumped into this packaging for Homebrew too. Unfortunately right now we have an all or nothing `--dilable-dependency-checks` which will work around this but at the cost of not doing lots of other useful checks. I'll look into something else in the future, but for this release if the font is not available at build time (and their is a plan to have it available at run time) probably the best thing to do is just patch out the `AX_FONT` line in `configure.ac`. For future releases maybe we can improve on that to not lump strongly suggested dependencies in with hard dependencies.

**Comment by alerque** [comment]
On second thought patching `configure.ac` is problematic because in requires rerunning `autoconf`, which may or may not be desirable. Another fix is to patch the macro that gets run to skip the checks. Here is what I worked up for Homebrew: <https://github.com/Homebrew/homebrew-core/pull/118254/commits/ac54e9919d3dd9326566853ba6ad26771251b36e>

**Comment by hegjon** [comment]
This will be an issue for all build systems where the build happens on a different machine than where it is running

**Comment by hegjon** [comment]
Would it be possible to have a alternative to `--disable-dependency-checks` that only checks for build dependencies?

**Comment by alerque** [comment]
Yes I'll look into an easier way to make the font dependency check optional while not loosing all the other checks. I already split out all the developer only dependencies, but build systems vary so much I didn't realize we'd need so much granular check control.

**Comment by hegjon** [comment]
It might not be a big issue, it would be great to have some smoke tests after the build, then the runtime dependencies needs to be installed.

**Comment by alerque** [comment]
There is already a smoke test available (`make check`) that requires runtime dependencies (in addition to `pdfinfo` as a check only dependency). Note that this will *not* be a failure without the default font because we're only testing that a valid PDF got created, not whether anything is metrically where we expect it as in the regression tests.

Most build systems have runtime plus build time dependencies available at build time. I'm a little surprised that's a problem on Fedora. Why can't the font be available at build time?

**Comment by hegjon** [comment]
> Most build systems have runtime plus build time dependencies available at build time. I'm a little surprised that's a problem on Fedora. Why can't the font be available at build time?

It is not a problem, I started the build without knowing that the script had been changed to also check for the font. The fix ended up adding the font as an build dependency.
