### ISSUE TITLE
v0.14.7 release checklist

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1667]
- [x] Shuffle any issues being put off to future milestones
- [x] Close all issues in current milestone (except this one)
- [x] Spring clean
    - [x] Re-fetch tooling
- [x] Configure and build
- [x] Pass all tests
    - [x] Remote CI
    - [x] Local
- [x] Cut release
- [x] Push release commit & tag to master
- Update website
    - [x] Copy and post manual, update 'latest' symlink and menu links
    - [x] Copy changelog and prefix with a summary as a blog post
    - [x] Tweak summary for gfm and edit into GitHub release notes
- Update downstream distro packages
	- [x] Arch Linux official: [community/sile](https://archlinux.org/packages/community/x86_64/sile/)
	- [x] Arch Linux AUR: [AUR/sile-luajit](https://aur.archlinux.org/packages/sile-luajit) 
    - [ ] Homebrew: [Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/sile.rb) – [pull request](https://github.com/Homebrew/homebrew-core/pull/118254)
    - [x] NixOS: [nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/sile/default.nix) – [pull request](https://github.com/NixOS/nixpkgs/pull/206284) – [tracker](https://nixpk.gs/pr-tracker.html?pr=206284)
        - [x] Drop devel flag from any website examples that were using it
    - [x] Ubuntu: [ppa](https://launchpad.net/~sile-typesetter/+archive/ubuntu/sile)
    - [x] Docker Hub: [tags](https://hub.docker.com/repository/docker/siletypesetter/sile/tags)
    - [x] GHCR: [versions](https://github.com/orgs/sile-typesetter/packages/container/sile/versions)
    - [ ] openSUSE: pinging @Pi-Cla re [specfile](https://build.opensuse.org/package/show/openSUSE%3AFactory/sile)
    - [x] Fedora: pinging @hegjon re [copr](https://copr.fedorainfracloud.org/coprs/jonny/SILE/)
    - [ ] NetBSD: pinging @jsonn re [pkgsrc](https://pkgsrc.se/print/sile)
    - [ ] Void Linux: 
    - [ ] OpenBSD: 
- Bump downstream projects
    - [ ] [FontProof](https://github.com/sile-typesetter/fontproof) (Docker image base plus CI matrix)
    - [ ] [CaSILE](https://github.com/sile-typesetter/casile) (check, consider patch release)
- [x] Eat cake

[![Packaging status](https://repology.org/badge/vertical-allrepos/sile.svg)](https://repology.org/project/sile/versions)

Previous release: #1653

**Comment by hegjon** [comment]
Building for Fedora/COPR https://copr.fedorainfracloud.org/coprs/jonny/SILE/build/5198407/

**Comment by hegjon** [comment]
New build https://copr.fedorainfracloud.org/coprs/jonny/SILE/build/5200186/

**Comment by Pi-Cla** [comment]
SR has been sent to openSUSE factory: https://build.opensuse.org/request/show/1056335

**Comment by alerque** [comment]
@hegjon All the -3N build series seem to have worked but rawhide failed. Dose that have to pass before it is available on all channels? Need any help debugging what happened?

**Comment by alerque** [comment]
Also just a heads up about the next release: Our HarfBuzz dependency is going to bump to minimum version of 6.0.0 for full feature support. It will be possible to build using old HarfBuzz versions by disabling variable font support, but for distro packages it would be really nice if we kept full feature parity across the board. Many distros already have 6.x packages available or in the works, but if not that's something you guys might want to flag and keep an eye on.

**Comment by hegjon** [comment]
> @hegjon All the -3N build series seem to have worked but rawhide failed. Dose that have to pass before it is available on all channels? Need any help debugging what happened?

Its only because of missing dependencies, Fedora created a new branch and the old dependencies were not added to the new branch. I rebuilt the dependencies for rawhide and rebuilt SILE for rawhide in the last build.

**Comment by hegjon** [comment]
> Also just a heads up about the **next release cycle**: Our HarfBuzz dependency is going to bump to minimum version of 6.0.0 for full feature support. It will be possible to build using old HarfBuzz versions by disabling variable font support, but for distro packages it would be really nice if we kept full feature parity across the board. Many distros already have 6.x packages available or in the works, but if not that's something you guys might want to flag and keep an eye on.

Thanks for the heads up, Fedora have bumped to version 6.0.1 for rawhide that will be Fedora 38 in April/May. Fedora 37 is shipping 5.2.0.

**Comment by alerque** [comment]
In that case for SILE v0.14.8 you'll need to build with `--disable-font-variations` on Fedora <= 37, and with default flags on rawhide and >= 38. If there is a place to document distro support notes it might be worth mentioning.

There will be one minor regression for existing users, but for the most part this will be a case of "you can't have nice things unless you upgrade your system".
