### ISSUE TITLE
v0.14.8 release checklist

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1677]
- [x] Shuffle any issues being put off to future milestones
- [x] Close all issues in current milestone (except this one)
- [x] Spring clean
    - [x] Re-fetch tooling
- [x] Configure and build
- [x] Pass all tests
    - [x] Remote CI
    - [x] Local
- [x] Cut release
- [x] Push release commit & tag to master
- Update website
    - [x] Copy and post manual, update 'latest' symlink and menu links
    - [x] Copy changelog and prefix with a summary as a blog post
    - [x] Tweak summary for gfm and edit into GitHub release notes
- Update downstream distro packages
	- [x] Arch Linux official: [community/sile](https://archlinux.org/packages/community/x86_64/sile/)
	- [x] Arch Linux AUR: [AUR/sile-luajit](https://aur.archlinux.org/packages/sile-luajit) 
    - [x] Homebrew: [Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/sile.rb) – [pull request](https://github.com/Homebrew/homebrew-core/pull/121638)
    - [x] NixOS: [nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/sile/default.nix) – [pull request](https://github.com/NixOS/nixpkgs/pull/212839) – [tracker](https://nixpk.gs/pr-tracker.html?pr=212839)
        - [x] Drop devel flag from any website examples that were using it
    - [x] Ubuntu: [ppa](https://launchpad.net/~sile-typesetter/+archive/ubuntu/sile)
    - [x] Docker Hub: [tags](https://hub.docker.com/repository/docker/siletypesetter/sile/tags)
    - [x] GHCR: [versions](https://github.com/orgs/sile-typesetter/packages/container/sile/versions)
    - [x] openSUSE: pinging @Pi-Cla re [specfile](https://build.opensuse.org/package/show/openSUSE%3AFactory/sile)
    - [x] Fedora: pinging @hegjon re [copr](https://copr.fedorainfracloud.org/coprs/jonny/SILE/)
    - [ ] NetBSD: pinging @jsonn re [pkgsrc](https://pkgsrc.se/print/sile)
    - [ ] Void Linux: 
    - [ ] OpenBSD: 
- Bump downstream projects
    - [ ] [FontProof](https://github.com/sile-typesetter/fontproof) (Docker image base plus CI matrix)
    - [x] [CaSILE](https://github.com/sile-typesetter/casile) (check, consider patch release)
- [x] Eat cake

[![Packaging status](https://repology.org/badge/vertical-allrepos/sile.svg)](https://repology.org/project/sile/versions)

Previous release: #1667

**Comment by alerque** [comment]
Note **for Ubuntu users**: All currently released/supported versions of Ubuntu have very old HarfBuzz libraries that will not support the new variable font support features. The upcoming 23.04 release will have 6.0.0. I'm going to push this SILE release to the PPA with variation support disabled for now. If there are active Ubuntu users out there willing to try an experiment, please ping me (maybe in a new issue). We can try giving you a back-ported HarfBuzz package along with a SILE build that uses it. If that plays nice with the rest of your system we could put that in the PPAs for everybody, but I don't use Ubuntu in any capacity myself other than running some builds like these so I don't feel safe pushing a HarfBuzz package to the PPA that everybody would get and *might* adversely affect the rest of the system without someone to test drive it first.

**Comment by hegjon** [comment]
Started builds for Fedora Linux at COPR: https://copr.fedorainfracloud.org/coprs/jonny/SILE/build/5331492/

Not sure this is the best way or if it is needed at all? Only Fedora rawhide have HarfBuzz 6.0.0.

```
export EXTRA_FLAGS="$(pkg-config --atleast-version 6.0.0 harfbuzz || echo --disable-font-variations)"
%configure $EXTRA_FLAGS \
  --disable-static \
  --with-system-luarocks \
```

Would be great if the configure script checked the version of HarfBuzz and did this check.

**Comment by alerque** [comment]
It already does do the version check and adjusts its minimums for the features you've requested, but it defaults to throwing an error rather than just quietly succeeding with reduced features. I want people to be explicitly aware that they were not getting the full toolbox, not just miss because configure found *some* version of HarfBuzz.

**Comment by Pi-Cla** [comment]
openSUSE Submit Request has been sent: https://build.opensuse.org/request/show/1061683

**Comment by Pi-Cla** [comment]
The SILE package has been updated on openSUSE TW wew
