### ISSUE TITLE
v0.14.11 release checklist

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1850]
- [x] Shuffle any issues being put off to future milestones
- [x] Close all issues in current milestone (except this one)
- [ ] Spring clean
    - [ ] Re-fetch tooling
- [ ] Configure and build
- [ ] Pass all tests
    - [ ] Remote CI
    - [ ] Local
- [ ] Cut release
- [ ] Push release commit & tag to master
- Update website
    - [ ] Copy and post manual, update 'latest' symlink and menu links
    - [ ] Copy changelog and prefix with a summary as a blog post
    - [ ] Tweak summary for gfm and edit into GitHub release notes
- Update downstream distro packages
	- [ ] Arch Linux official: [community/sile](https://archlinux.org/packages/community/x86_64/sile/)
	- [ ] Arch Linux AUR: [AUR/sile-luajit](https://aur.archlinux.org/packages/sile-luajit) 
    - [ ] Homebrew: [Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/sile.rb) 
    - [ ] NixOS: [nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/sile/default.nix) 
        - [ ] Drop devel flag from any website examples that were using it
    - [ ] Ubuntu: [ppa](https://launchpad.net/~sile-typesetter/+archive/ubuntu/sile)
    - [ ] Docker Hub: [tags](https://hub.docker.com/repository/docker/siletypesetter/sile/tags)
    - [ ] GHCR: [versions](https://github.com/orgs/sile-typesetter/packages/container/sile/versions)
    - [ ] openSUSE: 
    - [ ] Fedora: 
    - [ ] NetBSD: 
    - [ ] Void Linux: 
    - [ ] OpenBSD: 
- Bump downstream projects
    - [ ] [FontProof](https://github.com/sile-typesetter/fontproof) (Docker image base plus CI matrix)
    - [ ] [CaSILE](https://github.com/sile-typesetter/casile) (check, consider patch release)
- [ ] Eat cake

[![Packaging status](https://repology.org/badge/vertical-allrepos/sile.svg)](https://repology.org/project/sile/versions)

Previous checklist: #1830 ([release](https://github.com/sile-typesetter/sile/releases/tag/v0.14.10))
