### ISSUE TITLE
v0.14.12 release checklist

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1890]
- [x] Shuffle any issues being put off to future milestones
- [x] Close all issues in current milestone (except this one)
- [x] Spring clean
    - [x] Re-fetch tooling
- [x] Configure and build
- [x] Pass all tests
    - [x] Remote CI
    - [x] Local
- [x] Cut release
- [x] Push release commit & tag to master
- Update website
    - [x] Copy and post manual, update 'latest' symlink and menu links
    - [x] Copy changelog and prefix with a summary as a blog post
    - [x] Tweak summary for gfm and edit into GitHub release notes
- Update downstream distro packages
    - [x] Arch Linux: [extra/sile](https://archlinux.org/packages/extra/x86_64/sile/)
    - [x] Homebrew: [Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/s/sile.rb) – [pull request](https://github.com/Homebrew/homebrew-core/pull/150609)
    - [x] NixOS: [nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/sile/default.nix) – [pull request](https://github.com/NixOS/nixpkgs/pull/262061) – [tracker](https://nixpk.gs/pr-tracker.html?pr=262061)
        - [x] Drop devel flag from any website examples that were using it
    - [ ] Ubuntu: [ppa](https://launchpad.net/~sile-typesetter/+archive/ubuntu/sile)
    - [x] Docker Hub: [tags](https://hub.docker.com/repository/docker/siletypesetter/sile/tags)
    - [x] GHCR: [versions](https://github.com/orgs/sile-typesetter/packages/container/sile/versions)
    - [x] openSUSE: pinging @Pi-Cla re [specfile](https://build.opensuse.org/package/show/openSUSE%3AFactory/sile)
    - [x] Fedora: pinging @hegjon re [copr](https://copr.fedorainfracloud.org/coprs/jonny/SILE/)
    - [ ] NetBSD: pinging @jsonn re [pkgsrc](https://pkgsrc.se/print/sile)
    - [ ] Void Linux: [pull request](https://github.com/void-linux/void-packages/pull/18306)
    - [ ] OpenBSD: [mailing list thread](https://marc.info/?t=157907840200001)
- Bump downstream projects
    - [ ] [FontProof](https://github.com/sile-typesetter/fontproof) (Docker image base plus CI matrix)
    - [ ] [CaSILE](https://github.com/sile-typesetter/casile) (check, consider patch release)
- [ ] Eat cake

[![Packaging status](https://repology.org/badge/vertical-allrepos/sile.svg)](https://repology.org/project/sile/versions)

Previous checklist: #1850 ([release](https://github.com/sile-typesetter/sile/releases/tag/v0.14.11))
[This release](https://github.com/sile-typesetter/sile/releases/tag/v0.14.11)

**Comment by alerque** [comment]
Hmm, CaSILE can no longer be released until SILE 0.15.0 is out, the current HEAD depends of fixes found only in SILE's development branch (esp. in regard to Lua path handling).

**Comment by jodros** [comment]
I'm currently using Void and probably will keep using it, so I'd be glad to help to update its version in XBPS. Where could I begin from and what should I know to get into this release step??

**Comment by alerque** [comment]
@jodros I'd be glad to help some with Void. I suggest we revive my fork of the packaging repo and either I add you as a maintainer to my fork or vise versa so we can have a branch to work on. Or you can just pull my branch into your fork and open a draft PR so I can comment on it if you want to handle stuff.

The packaging is relatively similar to Arch Linux, so we can use that as a reference for what needs to happen and adjust the actual packaging manifest for Void norms. The main issue I ran into is Void needed more Lua packages for the dependencies and I didn't get around to adding them. Those are pretty similar, you find another one that is similar and just copy it and adjust the relevant bits.

**Comment by hegjon** [comment]
I run a smoke test as part of the RPM build for Fedora:
```
%check
echo -n '\document{foo}' | ./sile - -o foo.pdf
```

And it now fails:

```
/usr/bin/lua: ./core/utilities.lua:3: module 'semver' not found:
	no field package.preload['semver']
	no file './sile/semver.lua'
	no file './sile/semver/init.lua'
	no file './semver.lua'
	no file './semver/init.lua'
	no file '=[C]/sile/semver.lua'
	no file '=[C]/sile/semver/init.lua'
	no file '=[C]/semver.lua'
	no file '=[C]/semver/init.lua'
	no file '/usr/share/lua/5.4/sile/semver.lua'
	no file '/usr/share/lua/5.4/sile/semver/init.lua'
	no file '/usr/lib64/lua/5.4/sile/semver.lua'
	no file '/usr/lib64/lua/5.4/sile/semver/init.lua'
	no file '/usr/lib64/sile/lua-libraries/semver.lua'
	no file '/usr/lib64/sile/lua-libraries/semver/init.lua'
	no file '/usr/lib64/sile/semver.lua'
	no file '/usr/lib64/sile/semver/init.lua'
	no file '/usr/share/sile/lua-libraries/semver.lua'
	no file '/usr/share/sile/lua-libraries/semver/init.lua'
	no file '/usr/share/sile/semver.lua'
	no file '/usr/share/sile/semver/init.lua'
	no file '/usr/share/lua/5.4/semver.lua'
	no file '/usr/share/lua/5.4/semver/init.lua'
	no file '/usr/lib64/lua/5.4/semver.lua'
	no file '/usr/lib64/lua/5.4/semver/init.lua'
	no file './sile/semver.so'
	no file './semver.so'
	no file '=[C]/sile/semver.so'
	no file '=[C]/semver.so'
	no file '/usr/lib64/sile/semver.so'
	no file '/usr/share/sile/semver.so'
	no file '/usr/lib64/lua/5.4/semver.so'
	no file '/usr/lib64/lua/5.4/loadall.so'
stack traceback:
	[C]: in function 'require'
	./core/utilities.lua:3: in main chunk
	[C]: in function 'require'
	./core/sile.lua:35: in main chunk
	[C]: in function 'require'
	./sile:22: in main chunk
	[C]: in ?
``` 

File used for building: https://github.com/sile-typesetter/sile/releases/download/v0.14.12/sile-0.14.12.tar.xz

**Comment by alerque** [comment]
@hegjon This release added a file in the `lua-libraries` directory, `semver.lua`. In your case it should get installed to `/usr/share/sile/lua-libraries/semver.lua`, which I *do see* in the list of attempted paths. It should get there because it is part of the file list in `nobase_dist_pkgdata_DATA`. It is not clear to me how that is not working for you, especially since it *is* working on other platforms.

Are you sure you've built in a clean directory and *installed* the package you are testing with that smoke test?

**AHA** that's going to be your problem I think. You're running a smoke test using `./sile` from the source directory, but all the paths I see being used there are the paths it expects to find the **installed** library files. You have three options to run such a smoke test: you can use `./configure --enable-developer` to add special paths so that SILE can run in place from the source directory, or you can install it to the system and then check it from there (you shouldn't mix or match these two), or finally can test the release build from the source directory by manually running `export SILE_PATH=$(pwd)` first.

**Comment by hegjon** [comment]
. Will the `./configure --enable-developer` also include those extra paths for end-users installing it via the RPM package?

> Are you sure you've built in a clean directory and installed the package you are testing with that smoke test?

`%check` runs in-place, there are no files installed in this stage. There are some infrastructure for running integration tests for Fedora packages, where the package will be installed. This would be better, but adding it into `%check` was quick and easy.


Setting the `SILE_PATH` did not help:
```
export SILE_PATH=$(pwd)
echo -n '\document{foo}' | ./sile - -o foo.pdf
```

```
++ pwd
+ export SILE_PATH=/home/jonny/rpmbuild/BUILD/sile-0.14.12
+ SILE_PATH=/home/jonny/rpmbuild/BUILD/sile-0.14.12
+ echo -n '\document{foo}'
+ ./sile - -o foo.pdf
/usr/bin/lua: ./core/utilities.lua:3: module 'semver' not found:
	no field package.preload['semver']
	no file './sile/semver.lua'
	no file './sile/semver/init.lua'
	no file './semver.lua'
	no file './semver/init.lua'
	no file '=[C]/sile/semver.lua'
	no file '=[C]/sile/semver/init.lua'
	no file '=[C]/semver.lua'
	no file '=[C]/semver/init.lua'
	no file '/home/jonny/rpmbuild/BUILD/sile-0.14.12/sile/semver.lua'
	no file '/home/jonny/rpmbuild/BUILD/sile-0.14.12/sile/semver/init.lua'
	no file '/home/jonny/rpmbuild/BUILD/sile-0.14.12/semver.lua'
	no file '/home/jonny/rpmbuild/BUILD/sile-0.14.12/semver/init.lua'
	no file '/usr/share/lua/5.4/sile/semver.lua'
	no file '/usr/share/lua/5.4/sile/semver/init.lua'
	no file '/usr/lib64/lua/5.4/sile/semver.lua'
	no file '/usr/lib64/lua/5.4/sile/semver/init.lua'
	no file '/usr/lib64/sile/lua-libraries/semver.lua'
	no file '/usr/lib64/sile/lua-libraries/semver/init.lua'
	no file '/usr/lib64/sile/semver.lua'
	no file '/usr/lib64/sile/semver/init.lua'
	no file '/usr/share/sile/lua-libraries/semver.lua'
	no file '/usr/share/sile/lua-libraries/semver/init.lua'
	no file '/usr/share/sile/semver.lua'
	no file '/usr/share/sile/semver/init.lua'
	no file '/usr/share/lua/5.4/semver.lua'
	no file '/usr/share/lua/5.4/semver/init.lua'
	no file '/usr/lib64/lua/5.4/semver.lua'
	no file '/usr/lib64/lua/5.4/semver/init.lua'
	no file './sile/semver.so'
	no file './semver.so'
	no file '=[C]/sile/semver.so'
	no file '=[C]/semver.so'
	no file '/home/jonny/rpmbuild/BUILD/sile-0.14.12/sile/semver.so'
	no file '/home/jonny/rpmbuild/BUILD/sile-0.14.12/semver.so'
	no file '/usr/lib64/sile/semver.so'
	no file '/usr/share/sile/semver.so'
	no file '/usr/lib64/lua/5.4/semver.so'
	no file '/usr/lib64/lua/5.4/loadall.so'
stack traceback:
	[C]: in function 'require'
	./core/utilities.lua:3: in main chunk
	[C]: in function 'require'
	./core/sile.lua:35: in main chunk
	[C]: in function 'require'
	./sile:22: in main chunk
	[C]: in ?
+```

**Comment by alerque** [comment]
> Will the `./configure --enable-developer` also include those extra paths for end-users installing it via the RPM package?

Yes, which is not a good thing. That will add a hard coded path of the source directory you compiled in to everybody's search path. The developer mode flag should *not* be used for builds that get installed or packaged; it is only for enabling local testing conveniences.

If you want a smoke test, it does not make any sense to run it in place in the source directory because even if you add the necessary paths what you are testing is that the sources exist in the sources directory, not that the installation/packaging did all the right things. We already run unit tests here in CI, what you need is integration tests to check that it all works as installed.

For another example of a distro doing smoke tests after installation, see Nix:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/sile/default.nix#L75-L89

**Comment by alerque** [comment]
I'm also a bit confused because it my testing this particular smoke test *does* work when compiled with the options you used while still in that directory. As I said it is only a partial test, but it does work. I'm now quite puzzled why you stared tripping up on *that* file only now.

**Comment by alerque** [comment]
Okay it's working for me because of [this workaround](https://github.com/sile-typesetter/sile/blob/v0.14.12/core/pathsetup.lua.in#L64) we added for Nix Flakes, but actually catches the case of running Lua from a relative path from my system Lua as well.

Now I'm wondering why your system Lua is doing something different. Can you try this:

```console
$ cd /tmp
$ echo 'print(debug.getinfo(1, "S").source)' > test.lua
$ lua ./test.lua
@./test.lua
```

Does your Lua not output the leading `@` sign here? Note I intentionally ran this outside of the SILE source directory and just with the system Lua asking it to identify the path to the input file.

**Comment by alerque** [comment]
Now I'm even more confused, because I spun up a Fedora (40) Docker image from scratch and build the spec file myself (using your posted v0.14.10 as a base but switching the version to v0.14.12).

With nothing but `dnf install rpmdevtools dnf-plugins-core` and `dnf builddep sile.spec` to get dependencies and the source tarball and modified spec file, the `rpmbuild -bi sile.spec` completed successfully which runs your smoke test.

Back to you because I'm in over my head and yet it seems to be working. I don't know what is different about your setup.

**Comment by hegjon** [comment]
Running a build on COPR now for 0.14.12 https://copr.fedorainfracloud.org/coprs/jonny/SILE/build/6571793/

**Comment by hegjon** [comment]
Seems like it is my local dev environment that is causing issues, the build succeeded in all the matrix builds

**Comment by alerque** [comment]
@hegjon I'm still curious what was going on because you ran into some failure mode I don't understand and we clearly are not coding defensively enough to handle or give sensible errors. That being said since I can't replicate it at all I really don't know what to say or even check next. My suspicion is that you have somehow mix & matched sources from different versions, possibly with partial installations to the dev system that are tripping up the current sources in the current directory. If you want to try to sort it out or have any more input lets open a new issue to track down what's going on and if/how to fix it.
