### ISSUE TITLE
v0.14.15 release checklist

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1968]
- [x] Shuffle any issues being put off to future milestones
- [x] Close all issues in current milestone (except this one)
- [x] Spring clean
    - [x] Re-fetch tooling
- [x] Configure and build
- [x] Pass all tests
    - [x] Remote CI
    - [x] Local
- [x] Cut release
- [x] Push release commit & tag to master
- Update website
    - [x] Copy and post manual, update 'latest' symlink and menu links
    - [x] Copy changelog and prefix with a summary as a blog post
    - [x] Tweak summary for gfm and edit into GitHub release notes
- Update downstream distro packages
    - [x] Arch Linux: [extra/sile](https://archlinux.org/packages/extra/x86_64/sile/)
    - [ ] Homebrew: [Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/s/sile.rb) 
    - [ ] NixOS: [nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/sile/default.nix) 
        - [x] Drop devel flag from any website examples that were using it
    - [ ] Ubuntu: [ppa](https://launchpad.net/~sile-typesetter/+archive/ubuntu/sile)
    - [ ] Docker Hub: [tags](https://hub.docker.com/repository/docker/siletypesetter/sile/tags)
    - [x] GHCR: [versions](https://github.com/orgs/sile-typesetter/packages/container/sile/versions)
    - [ ] openSUSE: pinging @Pi-Cla re [specfile](https://build.opensuse.org/package/show/openSUSE%3AFactory/sile)
    - [ ] Fedora: pinging @hegjon re [copr](https://copr.fedorainfracloud.org/coprs/jonny/SILE/)
    - [ ] NetBSD: pinging @jsonn re [pkgsrc](https://pkgsrc.se/print/sile)
    - [ ] Void Linux: 
    - [ ] OpenBSD: 
- Bump downstream projects
    - [ ] [FontProof](https://github.com/sile-typesetter/fontproof) (Docker image base plus CI matrix)
    - [ ] [CaSILE](https://github.com/sile-typesetter/casile) (check, consider patch release)
- [ ] Eat cake

[![Packaging status](https://repology.org/badge/vertical-allrepos/sile.svg)](https://repology.org/project/sile/versions)

Previous checklist: #1942 ([release](https://github.com/sile-typesetter/sile/releases/tag/v0.14.14))
[This release](https://github.com/sile-typesetter/sile/releases/tag/v0.14.15)

**Comment by alerque** [comment]
Packagers don't bother, I'm going to tag v0.14.16 to fix a release tooling snafu. I tagged without pulling the latest upstream merge! No features are affected but the branching is all messed up now.
