### ISSUE TITLE
v0.14.17 release checklist

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1996]
- [x] Shuffle any issues being put off to future milestones
- [x] Close all issues in current milestone (except this one)
- [x] Spring clean
    - [x] Re-fetch tooling
- [x] Configure and build
- [x] Pass all tests
    - [x] Remote CI
    - [x] Local
- [x] Cut release
- [x] Push release commit & tag to master
- Update website
    - [x] Copy and post manual, update 'latest' symlink and menu links
    - [x] Copy changelog and prefix with a summary as a blog post
    - [x] Tweak summary for gfm and edit into GitHub release notes
- Update downstream distro packages
    - [x] Arch Linux: [extra/sile](https://archlinux.org/packages/extra/x86_64/sile/)
    - [x] Homebrew: [Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/s/sile.rb) – [pull request](https://github.com/Homebrew/homebrew-core/pull/162405)
    - [x] NixOS: [nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/sile/default.nix) – [pull request](https://github.com/NixOS/nixpkgs/pull/287175) – [tracker](https://nixpk.gs/pr-tracker.html?pr=287175)
        - [x] Drop devel flag from any website examples that were using it
    - [x] Ubuntu: [ppa](https://launchpad.net/~sile-typesetter/+archive/ubuntu/sile)
    - [x] Docker Hub: [tags](https://hub.docker.com/repository/docker/siletypesetter/sile/tags)
    - [x] GHCR: [versions](https://github.com/orgs/sile-typesetter/packages/container/sile/versions)
    - [x] openSUSE: pinging @Pi-Cla re [specfile](https://build.opensuse.org/package/show/openSUSE%3AFactory/sile)
    - [x] Fedora: pinging @hegjon re [copr](https://copr.fedorainfracloud.org/coprs/jonny/SILE/)
    - [ ] NetBSD: pinging @jsonn re [pkgsrc](https://pkgsrc.se/print/sile)
    - [ ] Void Linux: 
    - [ ] OpenBSD: 
- Bump downstream projects
    - [x] [FontProof](https://github.com/sile-typesetter/fontproof) (Docker image base plus CI matrix)
    - [x] [CaSILE](https://github.com/sile-typesetter/casile) (check, consider patch release)
- [x] Eat cake

[![Packaging status](https://repology.org/badge/vertical-allrepos/sile.svg)](https://repology.org/project/sile/versions)

Previous checklist: #1972 ([release](https://github.com/sile-typesetter/sile/releases/tag/v0.14.16))
[This release](https://github.com/sile-typesetter/sile/releases/tag/v0.14.17)

**Comment by Omikhleia** [comment]
@alerque in the release note: "Additionally Jakub contributed an option for columns command to more easily set up column frames" --> Unless mistaken, tt's @jodros I think ;)

**Comment by alerque** [comment]
Thanks. Yes I goofed that copy. I actually caught it before posting the website version but forgot I'd already copied the text into the release notes.

**Comment by hegjon** [comment]
Build successful on COPR for Fedora https://copr.fedorainfracloud.org/coprs/jonny/SILE/build/7000270/

**Comment by n7s** [comment]
Thanks for all the work! It would be lovely to have the Ubuntu PPA provide packages for noble (the upcoming Ubuntu LTS). Çok teşekkürler!

**Comment by alerque** [comment]
Last I checked (when I cut v0.14.16) the LXD images and PPA builders I use to push packaging through didn't fully support noble, but I'll check again.

**Comment by n7s** [comment]
I can confirm that I have access to a noble lxc image here for testing. Until the image hosting situation improves (lxc/d/incus issues), you can simply add a remote: 
`lxc remote add --protocol simplestreams ubuntu-daily https://cloud-images.ubuntu.com/`  

then     `lxc launch ubuntu-daily:noble`

Yes this is pre-release, but it would be nice to be able to test it.

**Comment by alerque** [comment]
Thanks for the tip @n7s, my `apt`ly named [ppa-zookeeper](https://github.com/alerque/que-utils/blob/master/bin/ppa-zookeeper) now has support for *noble numbat*, and [Robert is your father's brother](https://launchpad.net/~sile-typesetter/+archive/ubuntu/sile/+packages?field.name_filter=&field.status_filter=published&field.series_filter=noble).

**Comment by Omikhleia** [comment]
@alerque No urge but just in case: https://sile-typesetter.org/manual/sile-latest.pdf gave me a 404.

**Comment by alerque** [comment]
@Omikhleia Thanks, it looks like I missed a `git add` in there, it should be posted in a second.

**Comment by n7s** [comment]
fantastic, we really appreciate all your work in handling the whole zoo!
