### ISSUE TITLE
v0.15.0 release checklist

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#2000]
- [x] Shuffle any issues being put off to future milestones
- [x] Close all issues in current milestone (except this one)
- [x] Spring clean
    - [x] Re-fetch tooling
- [x] Configure and build
- [x] Pass all tests
    - [x] Remote CI
    - [x] Local
- [x] Cut release
- [x] Push release commit & tag to master
- Update website
    - [x] Copy and post manual, update 'latest' symlink and menu links
    - [x] Copy changelog and prefix with a summary as a blog post
    - [x] Tweak summary for gfm and edit into GitHub release notes
- Update downstream distro packages
    - [x] Arch Linux: [extra/sile](https://archlinux.org/packages/extra/x86_64/sile/)
    - [ ] Homebrew: [Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/s/sile.rb) 
    - [ ] NixOS: [nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/sile/default.nix) 
        - [ ] Drop devel flag from any website examples that were using it
    - [ ] Ubuntu: [ppa](https://launchpad.net/~sile-typesetter/+archive/ubuntu/sile)
    - [ ] Docker Hub: [tags](https://hub.docker.com/repository/docker/siletypesetter/sile/tags)
    - [ ] GHCR: [versions](https://github.com/orgs/sile-typesetter/packages/container/sile/versions)
    - [ ] openSUSE: 
    - [ ] Fedora: 
    - [ ] NetBSD: 
    - [ ] Void Linux: 
    - [ ] OpenBSD: 
- Bump downstream projects
    - [ ] [FontProof](https://github.com/sile-typesetter/fontproof) (Docker image base plus CI matrix)
    - [ ] [CaSILE](https://github.com/sile-typesetter/casile) (check, consider patch release)
- [ ] Eat cake

[![Packaging status](https://repology.org/badge/vertical-allrepos/sile.svg)](https://repology.org/project/sile/versions)

Previous checklist: #1996 ([release](https://github.com/sile-typesetter/sile/releases/tag/v0.14.17))
[This release](https://github.com/sile-typesetter/sile/releases/tag/v0.15.0)

**Comment by alerque** [comment]
Not all is quite smooth sailing. The source tarball has trouble building some bundled Lua Rocks. (Building from Git clones works fine.) Also Git shouldn't still be a dependency. Also the website wouldn't post the blog post because of some font trouble. There will probably be a patch release close on the heals of this, but first I need some sleep.

**Comment by alerque** [comment]
Also there are some deprecation messages being thrown from our own internals now that the version is actually bumped internally and that's pretty obnoxious...

**Comment by alerque** [comment]
Skipping ahead to v0.15.1 to address the missing source artifact and also touch up some paragraph handling snafus.
