### ISSUE TITLE
v0.15.1 release checklist

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#2046]
- [x] Shuffle any issues being put off to future milestones
- [x] Close all issues in current milestone (except this one)
- [x] Spring clean
    - [x] Re-fetch tooling
- [x] Configure and build
- [x] Pass all tests
    - [x] Remote CI
    - [x] Local
- [x] Cut release
- [x] Push release commit & tag to master
- [x] Download release artifacts, GPG sign, and upload signatures
- [x] Publish release build to [craties.io](https://crates.io/crates/sile)
- Update website
    - [x] Copy and post manual, update 'latest' symlink and menu links
    - [x] Copy changelog and prefix with a summary as a blog post
    - [ ] Tweak summary for gfm and edit into GitHub release notes
- Update downstream distro packages
    - [ ] Arch Linux: [extra/sile](https://archlinux.org/packages/extra/x86_64/sile/)
    - [ ] Homebrew: [Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/s/sile.rb) 
    - [ ] NixOS: [nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/sile/default.nix) 
        - [x] Drop devel flag from any website examples that were using it
    - [ ] Ubuntu: [ppa](https://launchpad.net/~sile-typesetter/+archive/ubuntu/sile)
    - [ ] Docker Hub: [tags](https://hub.docker.com/repository/docker/siletypesetter/sile/tags)
    - [ ] GHCR: [versions](https://github.com/orgs/sile-typesetter/packages/container/sile/versions)
    - [ ] openSUSE: 
    - [ ] Fedora: 
    - [ ] NetBSD: 
    - [ ] Void Linux: 
    - [ ] OpenBSD: 
- Bump downstream projects
    - [ ] [FontProof](https://github.com/sile-typesetter/fontproof) (Docker image base plus CI matrix)
    - [ ] [CaSILE](https://github.com/sile-typesetter/casile) (check, consider patch release)
- [ ] Eat cake

[![Packaging status](https://repology.org/badge/vertical-allrepos/sile.svg)](https://repology.org/project/sile/versions)

Previous checklist: #2000 ([release](https://github.com/sile-typesetter/sile/releases/tag/v0.15.0))
[This release](https://github.com/sile-typesetter/sile/releases/tag/v0.15.1)
