### ISSUE TITLE
Epic: Unsupported MathML elements and attributes

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#2138]
This is an "Epic" (in the sense of a parent issue for related sub-issues)

Maybe this is lost in some old discussion on some of the MathML implementation issue? Anyhow, here's a list (to be enriched possibly).

Some constructs SILE's MathML implementation does not support as of **v0.15.5**:
 - [ ] multiscripts (f2) - and mprescripts
 - [x] mstyle (f6) - this one is legacy in MathML Core = layout as mrow (at least) = #2151; see below for styling
 - [x] mpadded (f22) - see #2151 
 - [x] mtext (f18, f19, f22) - honestly this one is _much_ needed and shouldn't be complex... see #2140
 - [x] mphantom (f22) - see #2143
 - [x] msqrt - see #2119
 - [x] mroot - see #2120 
 - [x] ms - see #2140
 - [x] maction - MathML core says it can be considered as an mrow where only the first child is rendered = see #2151
 - [x] menclose - not in MathML Core, only MathML 3-4, but in the absence of CSS it's useful. MathJax supports it. - see #2318

Some other unsupported things
 - [ ] Most attributes on elements, ex.
    - [x] "linethickness" on mfrac (f10), -- see #2151 
    - [x] "form" on mo (for mphantom esp.),
    - [ ] Consistent support of "displaystyle" and "scriptlevel" on several tags - interesting in several cases (e.g. TeX cfrac)
    - [x] mathcolor, mathbackground - see #2340 
    - etc. (but what else would we want?)
 - [x] Improper sizing of some parentheses (several cases) - #2151 addressed the stretchy attribute and I think that was it!
 - [x] Stretchy horizontal braces (f19; f22) - some naive solution proposed in #2151 (test-based, maybe not general)
 - [x] Very large stretchy operators (whether done by glyph assembly or **faked**, they must be improved)
     - [x] Very large vertical stretchy parentheses (f23) - see  #2151 (achieved with a **hack**/workaround)
     - [x] Very large vertical stretchy determiner bar (f24) - same **hack** comment as previous

Other topics
 - Styling ought to be discussed. MathML core makes many attributes and the mstyle element legacy, but uses CSS instead... A hornets' nest...

Notes
 - For cross-checking see also https://w3c.github.io/mathml-core/#mathml-elements-and-attributes
 - The (f-numbers) above are the tests in https://fred-wang.github.io/MathFonts/mozilla_mathml_test/ - Whatever the status of this (old) 30-scenario Firefox MathML test, having the numbered items above would imply it passes for us (all other unmentioned tests are _already_ passing).

**Comment by Omikhleia** [comment]
Besides the above-mentioned old Firefox test, another interesting test to check: http://eyeasme.com/Joe/MathML/MathML_browser_test.html

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Omikhleia** [comment]
And of course, another great series of examples and checks... is just the MathML [test suite](https://www.w3.org/Math/testsuite/build/main/toc-full.xhtml)... I just started trying some of the "torture" tests, and it's... interesting ;)
