### ISSUE TITLE
Normalize release process

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#588]
Building a source release should be a one step process. The `Makefile` should have everything necessary to build and validate an entire release. The impact on the repository should be one commit.

Things that need to happen as part of a release (not necessarily all done from one command, but all the things that need to happen to cut a release).

## General todo

- [x] Add configure flags to prefer system Lua libraries over bundled ones where 
possible, see #659.
- [x] Make sure `lua_modules` ~~and `.fonts`~~ are populated and included in the source tarball, e.g. see #659.
- [x] Make sure paths in tarball on release tags don't have extra strings

## Things to happen Pre-release

- [x] Version numbers in `core/sile.lua` and `configure.ac` updated, started in #590 and operational in #758.
- [x] ~~Recompile (serialize?) languages with hyphenators, see #633.~~
- [x] Make sure the libtexpdf submodule SHA is current

## Things to happen at Release

- [x] Tag a new release number
- [x] `make docs` to include an up to date manual build in source tarballs (See #585)
- [x] `make examples` to regenerate examples and add PDF/PNG resources referenced in documentation (and/or website), e.g. see #595 
- [x] Tag the commit with the release version number
- [x] Push tags (and start a release on Github?), see #759.
- [x] Validate release: build from tarball and run tests (CI deploy script)
- [x] Check that the changelog (`NEWS.md`) contains an entry for the new version
- [x] Attach binary release artifacts from CI builds (Linux, Windows) to Github release tag (CI deploy script)

## Things to happen Post-release

- [x] Attach latest manual and examples to _____ (Github release? Release blog post?)
- [x] Add a make target to summarize changes since last release for `NEWS.md` editor (See below)  and post to gh-pages branch.
- [x] The manual also to be updated in the gh-pages branch
- [x] Ping distro packagers
- [x] Update Github milestones and bump any remaining issue to next

**Comment by simoncozens** [comment]
The version number in `core/sile.lua` should probably be filled in by autoconf anyway, so it's not manually repeated in different places.

**Comment by alerque** [comment]
I plan to generate the release number from `git describe --tags` anyway, so it will always be current any time `make` is run. We can add it to PDF meta data too ;-)

**Comment by simoncozens** [comment]
I still want the changelog written by hand, but I found it useful in the past to have a summary of the commits for the changelog editor to use for reference, e.g.:

```
git log --pretty=format:'%h %d %s <%an>' --abbrev-commit c36bddc...HEAD  > changes-0.9.5
```

Obviously we should have it generate the list from the last release to the current.

**Comment by alerque** [comment]
@simoncozens I'm working on release lifecycle tooling. What do you think about having a CHANGELOG.md that is developer-friendly and technical (and fully automated) in parallel with a NEWS.md file that is end-user friendly and promotional (and hand curated). We haven't been using conventional-commits quite right yet (I for one didn't understand the ramifications of `fix:` as opposed to `chore:` or `refactor:` and we should have been using `fix:` a lot less) but I think that automated output is actually going to be pretty useful. It's the kind of output I want to see when I review a new release.

I understand only developers (not SILE developers specifically, just developer type folks) will really be interested in that and a more user friendly release announcement and rundown of changes is necessary, but I think I'd like to see that happen either in parallel in NEWS.md (and prion/asynchronously to the release process) or even just on the release blog (do non-technical end users care that a user friendly news file is bundled in the source packages?).

**Comment by alerque** [comment]
For reference, automated change logs now look something like this:

https://github.com/alerque/sile/blob/46184feb7e0cd68a81406ce8beea3302d9e14971/CHANGELOG.md

**Comment by alerque** [comment]
All the stuff that is going to be automatic for the next release cycle already is.

See the [release checklist](https://github.com/sile-typesetter/sile/wiki/Release-Checklist) wiki page for the rest.
