### ISSUE TITLE
v0.10.0 release checklist

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#778]
See full [release checklist](https://github.com/sile-typesetter/sile/wiki/Release-Checklist/_edit) for howto, this is just a checklist version:

- [x] Pass all tests
- [x] Spring clean
- [x] Refetch tooling
- [x] Configure
- [x] Cut release
- [x] Make source
- Upload artifacts
    - [x] Push tag to master
    - [x] Open Github release on tag
    - [x] Attach tar.bz2
    - [x] Attach manual (renamed with version number)
- Update website
    - [x] Write summary version of changelog as blog post
    - [x] Copy and post manual, update latest and menu links
    - [x] Tweak summary and edit into Github release notes
- Update distro packages
    - [x] Arch Linux
    - [ ] Void Linux: [Pull Request](https://github.com/void-linux/void-packages/pull/18306)
    - [ ] NixOS: [Pull Request](https://github.com/NixOS/nixpkgs/pull/77738)
    - [x] Homebrew: [Pull Request](https://github.com/Homebrew/homebrew-core/pull/48995)
    - [ ] BSD Ports: [ports mailinglist thread](https://marc.info/?t=157907840200001)
    - [x] Docker
- [x] Shuffle milestones
- [x] Eat cake

**Comment by alerque** [comment]
Closing in favor of #794, incomplete distros can jump to v0.10.1. The open PR's here can be bumped in place.
