### ISSUE TITLE
v0.10.4 release checklist

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#852]
See full [release checklist](https://github.com/sile-typesetter/sile/wiki/Release-Checklist) for howto, this is just a checklist version:

- [x] Pass all tests
- [x] Spring clean
- [x] Re-fetch tooling
- [x] Configure
- [x] Cut release
- [x] Make source
- Upload artifacts
    - [x] Push tag to master
    - [x] Open Github release on tag
    - [x] Attach tar.bz2
    - [x] Attach manual (renamed with version number)
- Update website
    - [x] Write summary version of changelog as blog post
    - [x] Copy and post manual, update latest and menu links
    - [x] Tweak summary and edit into Github release notes
- Update distro packages
    - [x] Arch Linux
    - [ ] Void Linux: [Pull Request](https://github.com/void-linux/void-packages/pull/18306)
    - [x] NixOS: [Pull Request](https://github.com/NixOS/nixpkgs/pull/85739)
    - [x] Homebrew: [Pull Request](https://github.com/Homebrew/homebrew-core/pull/53500)
    - [ ] BSD Ports: [mailing list thread](https://marc.info/?t=157907840200001)
    - [x] Ubuntu: [ppa](https://launchpad.net/~sile-typesetter/+archive/ubuntu/sile)
    - [x] Docker
- [x] Shuffle milestones
- [ ] Eat cake

**Comment by alerque** [comment]
Ubuntu PPA finally updated (I 'broke' lockdown long enough to sneak into my office that had LXC images for building on Ubuntu). This time I made [some notes](https://github.com/sile-typesetter/sile/wiki/PPA-Update-Notes).

The obsolete packages on Void Linux and BSD are pretty much out of our hands at this point because they need a developer on those platforms to intervene. I'd go ahead and close this issue, but I don't have any cake handy.

**Comment by hmslima** [comment]
Sorry if this is the wrong place to comment it, but I am having problems in installing SILE in Kubuntu 20.04 through PPA. The lines below have some few texts in Portuguese, but I will provide translations for them, don't worry.

```
sudo add-apt-repository ppa:sile-typesetter/sile
[sudo] senha para hmslima: ********
 
 Mais informações: https://launchpad.net/~sile-typesetter/+archive/ubuntu/sile
Prima [ENTER] para continuar ou Ctrl+C para cancelar a sua adição.

Atingido:1 http://br.archive.ubuntu.com/ubuntu focal InRelease
Obter:2 http://br.archive.ubuntu.com/ubuntu focal-updates InRelease [107 kB]
Ign:3 http://ppa.launchpad.net/sile-typesetter/sile/ubuntu focal InRelease
Atingido:4 http://ppa.launchpad.net/starws-box/deadbeef-player/ubuntu focal InRelease
Obter:5 http://br.archive.ubuntu.com/ubuntu focal-backports InRelease [98,3 kB]               
Err:6 http://ppa.launchpad.net/sile-typesetter/sile/ubuntu focal Release                  
  404  Not Found [IP: 91.189.95.83 80]
Obter:7 http://br.archive.ubuntu.com/ubuntu focal-updates/main i386 Packages [59,8 kB]                                                                                                                                                                                        
Obter:8 http://security.ubuntu.com/ubuntu focal-security InRelease [107 kB]                                                                                                                                                                                                   
Obter:9 http://br.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [122 kB]                                                                                                                                                                                        
Obter:10 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [71,5 kB]                                                                                                                                                                                       
Obter:11 http://security.ubuntu.com/ubuntu focal-security/main i386 Packages [26,8 kB]                                                                                                                                                                                        
Obter:12 http://security.ubuntu.com/ubuntu focal-security/main Translation-en [27,0 kB]                                                                                                                                                                                       
Obter:13 http://security.ubuntu.com/ubuntu focal-security/main amd64 DEP-11 Metadata [16,6 kB]                                                                                                                                                                                
Obter:14 http://security.ubuntu.com/ubuntu focal-security/main amd64 c-n-f Metadata [2.004 B]                                                                                                                                                                                 
Obter:15 http://security.ubuntu.com/ubuntu focal-security/universe amd64 DEP-11 Metadata [208 B]                                                                                                                                                                              
Obter:16 http://br.archive.ubuntu.com/ubuntu focal-updates/main Translation-en [44,6 kB]                                                                                                                                                                                      
Obter:17 http://br.archive.ubuntu.com/ubuntu focal-updates/main amd64 DEP-11 Metadata [90,4 kB]                                                                                                                                                                               
Obter:18 http://br.archive.ubuntu.com/ubuntu focal-updates/main amd64 c-n-f Metadata [2.804 B]                                                                                                                                                                                
Obter:19 http://br.archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [68,3 kB]                                                                                                                                                                                  
Obter:20 http://br.archive.ubuntu.com/ubuntu focal-updates/universe i386 Packages [27,3 kB]                                                                                                                                                                                   
Obter:21 http://br.archive.ubuntu.com/ubuntu focal-updates/universe Translation-en [28,3 kB]                                                                                                                                                                                  
Obter:22 http://br.archive.ubuntu.com/ubuntu focal-updates/universe amd64 DEP-11 Metadata [136 kB]                                                                                                                                                                            
Obter:23 http://br.archive.ubuntu.com/ubuntu focal-updates/universe DEP-11 48x48 Icons [66,0 kB]                                                                                                                                                                              
Obter:24 http://br.archive.ubuntu.com/ubuntu focal-updates/universe DEP-11 64x64 Icons [104 kB]                                                                                                                                                                               
Obter:25 http://br.archive.ubuntu.com/ubuntu focal-updates/universe DEP-11 128x128 Icons [264 kB]                                                                                                                                                                             
Obter:26 http://br.archive.ubuntu.com/ubuntu focal-updates/universe amd64 c-n-f Metadata [2.128 B]                                                                                                                                                                            
Obter:27 http://br.archive.ubuntu.com/ubuntu focal-backports/universe amd64 DEP-11 Metadata [532 B]                                                                                                                                                                           
Lendo listas de pacotes... Pronto                                                                                                                                                                                                                                             
E: The repository 'http://ppa.launchpad.net/sile-typesetter/sile/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
hmslima@hmslima-pc:~$ sudo apt-get update
Atingido:1 http://br.archive.ubuntu.com/ubuntu focal InRelease
Atingido:2 http://br.archive.ubuntu.com/ubuntu focal-updates InRelease
Atingido:3 http://br.archive.ubuntu.com/ubuntu focal-backports InRelease
Atingido:4 http://security.ubuntu.com/ubuntu focal-security InRelease 
Ign:5 http://ppa.launchpad.net/sile-typesetter/sile/ubuntu focal InRelease
Atingido:6 http://ppa.launchpad.net/starws-box/deadbeef-player/ubuntu focal InRelease
Err:7 http://ppa.launchpad.net/sile-typesetter/sile/ubuntu focal Release
  404  Not Found [IP: 91.189.95.83 80]
Lendo listas de pacotes... Pronto                  
E: The repository 'http://ppa.launchpad.net/sile-typesetter/sile/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

* `senha para hmslima:` = `password for hmslima:`
* `Mais informações:` = `More information`
* `Prima [ENTER] para continuar ou Ctrl+C para cancelar a sua adição` = `Press [ENTER] to continue * or Ctrl+C in order to cancel  your addition`
* `Atingido` = `Archieving` if I am not mistaken...
* `Obter` = `To obtain`
* `Lendo listas de pacotes... Pronto` = `Reading list of packages... Ready`

And when I try to install SILE through the command `sudo apt-get install sile`, I get the message `Impossible to find the package sile`

**Comment by alerque** [comment]
@hmslima Thanks for the report. I believe the issue is that the PPA does not have 20.04 packages yet (which hadn't been released when I setup packaging). I'll look into adding builds against Focal...

**Comment by hmslima** [comment]
Thank you, I hope it doesn't take too long, I am anxious to test this software. 🙂

**Comment by alerque** [comment]
@hmslima You might try it now ;-) I've added Ubuntu 20.04 packages for SILE and all the dependencies that didn't make it into Ubuntu yet. Actually one package is still building, but it's already 4am and I'm going to bed, so either it works or it doesn't ;-) You can check the build status [here](https://launchpad.net/~sile-typesetter/+archive/ubuntu/sile/+packages).

Let me know if you have any trouble and I'll poke it again.

**Comment by alerque** [comment]
I'm closing this issue, but please comment on #833 if there are issues with the Focal packaging.
