### ISSUE TITLE
v0.10.6 release checklist

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#952]
See full [release checklist](https://github.com/sile-typesetter/sile/wiki/Release-Checklist) for howto, this is just a checklist version:

- [x] Pass all tests
- [x] Spring clean
- [x] Re-fetch tooling
- [x] Configure
- [x] Cut release
- [x] Make source
- Upload artifacts
    - [x] Push tag to master
    - ~~[ ] Open Github release on tag~~
    - ~~[ ] Attach tar.bz2~~
    - ~~[ ] Attach manual (renamed with version number)~~
- Update website
    - [x] Write summary version of changelog as blog post
    - [x] Copy and post manual, update latest and menu links
    - [x] Tweak summary and edit into Github release notes
- Update distro packages
    - [x] Arch Linux
    - [ ] Void Linux: [Pull Request](https://github.com/void-linux/void-packages/pull/18306)
    - [ ] NixOS: 
    - [ ] Homebrew: 
    - [ ] BSD Ports: [mailing list thread](https://marc.info/?t=157907840200001)
    - [ ] Ubuntu: [ppa](https://launchpad.net/~sile-typesetter/+archive/ubuntu/sile)
    - [x] Docker
- [x] Shuffle milestones
- [ ] Eat cake

(Note if this release goes right the Github Release will get opened with the right stuff attached automatically after pushing the tag.)

**Comment by alerque** [comment]
That did not go as planned. Since the main point of this exersize was to make sure downstream distro packaging works with Github Actions built packages I'm going immediately to another release.

Closing in favor of #954.
