### ISSUE TITLE
v0.10.7 release checklist

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#954]
See full [release checklist](https://github.com/sile-typesetter/sile/wiki/Release-Checklist) for howto, this is just a checklist version:

- [x] Pass all tests
- [x] Spring clean
- [x] Re-fetch tooling
- [x] Configure
- [x] Cut release
- [x] Make source
- [x] Push tag to master
- Update website
    - [x] Write summary version of changelog as blog post
    - [x] Copy and post manual, update latest and menu links
    - [x] Tweak summary and edit into Github release notes
- Update distro packages
    - [x] Arch Linux
    - [ ] Void Linux: [Pull Request](https://github.com/void-linux/void-packages/pull/18306)
    - [ ] NixOS: [Pull Request](https://github.com/NixOS/nixpkgs/pull/92152)
    - [x] Homebrew: [Pull Request](https://github.com/Homebrew/homebrew-core/pull/58131)
    - [ ] BSD Ports: [mailing list thread](https://marc.info/?t=157907840200001)
    - [x] Ubuntu: [ppa](https://launchpad.net/~sile-typesetter/+archive/ubuntu/sile)
    - [x] Docker
- [x] Shuffle milestones
- [ ] Eat cake

(Note if this release goes right the Github Release will get opened with the right stuff attached automatically after pushing the tag.)

**Comment by alerque** [comment]
Closing in favor of [v0.10.8](https://github.com/sile-typesetter/sile/issues/960).
