### ISSUE TITLE
v0.10.8 release checklist

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#960]
See full [release checklist](https://github.com/sile-typesetter/sile/wiki/Release-Checklist) for howto, this is just a checklist version:

- [x] Pass all tests
- [x] Spring clean
- [x] Re-fetch tooling
- [x] Configure
- [x] Cut release
- [x] Push tag to master
- Update website
    - [x] Copy changelog and prefix with a summary as a blog post
    - [x] Copy and post manual, update 'latest' symlink and menu links
    - [x] Tweak summary and edit into Github release notes
- Update distro packages
    - [x] Arch Linux
    - [ ] Void Linux: [Pull Request](https://github.com/void-linux/void-packages/pull/18306)
    - [ ] NixOS: [Pull Request](https://github.com/NixOS/nixpkgs/pull/92152)
    - [ ] Homebrew: [Pull Request](https://github.com/Homebrew/homebrew-core/pull/58199)
    - [ ] BSD Ports: [mailing list thread](https://marc.info/?t=157907840200001)
    - [x] Ubuntu: [ppa](https://launchpad.net/~sile-typesetter/+archive/ubuntu/sile)
    - [x] Docker
- [x] Shuffle milestones
- [ ] Eat cake

**Comment by alerque** [comment]
# EMERGENCY OOPS

I pushed a branch that had a broken commit that I thought I'd stuffed in another branch before running `make release`. Because branch protection was turned off to get the tags push through to master, CI didn't get run. It wouldn't have passed — the entire build system was in infinite loop mode.

I've backed the tag out, sorry for the inconvenience.

**Comment by alerque** [comment]
Closing in favor of https://github.com/sile-typesetter/sile/issues/967.
