### ISSUE TITLE
v0.10.9 release checklist

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#967]
See full [release checklist](https://github.com/sile-typesetter/sile/wiki/Release-Checklist) for howto, this is just a checklist version:

- [x] Pass all tests
- [x] Spring clean
- [x] Re-fetch tooling
- [x] Configure
- [x] Cut release
- [x] Push tag to master
- Update website
    - [x] Copy changelog and prefix with a summary as a blog post
    - [x] Copy and post manual, update 'latest' symlink and menu links
    - [x] Tweak summary and edit into Github release notes
- Update distro packages
    - [x] Arch Linux
    - [ ] Void Linux: [Pull Request](https://github.com/void-linux/void-packages/pull/18306)
    - [x] NixOS: ~~[Pull Request](https://github.com/NixOS/nixpkgs/pull/92152)~~ [Pull Request](https://github.com/NixOS/nixpkgs/pull/94168)
    - [x] Homebrew: [Pull Request](https://github.com/Homebrew/homebrew-core/pull/58199)
    - [ ] BSD Ports: [mailing list thread](https://marc.info/?t=157907840200001)
    - [x] Ubuntu: [ppa](https://launchpad.net/~sile-typesetter/+archive/ubuntu/sile)
    - [x] Docker
- [x] Shuffle milestones
- [x] Eat cake

**Comment by alerque** [comment]
@simoncozens Can you do a quick check on macOS to make sure the current master builds? Preferably from the build artifacts rather from Git, since that's where the last release [ran into trouble for Homebrew](). The [build page here](https://github.com/sile-typesetter/sile/actions/runs/176146583) has the current artifacts for master. Yes it is double zipped (not our bug). After double unzipping and `cd`ing in, it should be a matter of `./configure && make && make check`.

**Comment by alerque** [comment]
Actually maybe wait until I get #968 nailed down.

**Comment by alerque** [comment]
I'm going to call this done. Updating Void Linux and FreeBSD are completely out of our hands and needs somebody on those platforms to take ownership of the packing. I'm happy to help facilitate either one, but I don't consider this something we need to track on our end because there doesn't seem to be anything further the SILE end of things can do.
